apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-code-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: build-code
  template:
    metadata:
      labels:
        app: build-code
    spec:
      serviceAccountName: ecr-puller-sa
      containers:
      - name: build-code
        image: 026090560085.dkr.ecr.us-east-2.amazonaws.com/k8s-goat-build-code:latest
        resources:
          limits:
            memory: "50Mi"
            cpu: "20m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: build-code-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: build-code
